## **Library import**

In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import MinMaxScaler

## **Loading CSV File**

In [2]:
df = pd.read_csv("breast-cancer-wisconsin.csv")
df.shape

(699, 11)

## **Dropping missing values row if any**

In [3]:
df.replace("?",np.nan,inplace=True)
df.dropna(inplace=True)
df.shape

(683, 11)

## **Extracting Class Column and dropping it from data frame**

In [4]:
target = df["Class"]
df.drop(columns=["Class", "Sample"], inplace=True)
df

F1  F2  F3  F4  F5  F6  F7  F8  F9
0     5   1   1   1   2   1   3   1   1
1     5   4   4   5   7  10   3   2   1
2     3   1   1   1   2   2   3   1   1
3     6   8   8   1   3   4   3   7   1
4     4   1   1   3   2   1   3   1   1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..
694   3   1   1   1   3   2   1   1   1
695   2   1   1   1   2   1   1   1   1
696   5  10  10   3   7   3   8  10   2
697   4   8   6   4   3   4  10   6   1
698   4   8   8   5   4   5  10   4   1

[683 rows x 9 columns]

## **Scaling Data using Min-Max Scaler**

In [5]:
scaler = MinMaxScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
df

F1        F2        F3        F4        F5        F6        F7  \
0    0.444444  0.000000  0.000000  0.000000  0.111111  0.000000  0.222222   
1    0.444444  0.333333  0.333333  0.444444  0.666667  1.000000  0.222222   
2    0.222222  0.000000  0.000000  0.000000  0.111111  0.111111  0.222222   
3    0.555556  0.777778  0.777778  0.000000  0.222222  0.333333  0.222222   
4    0.333333  0.000000  0.000000  0.222222  0.111111  0.000000  0.222222   
..        ...       ...       ...       ...       ...       ...       ...   
678  0.222222  0.000000  0.000000  0.000000  0.222222  0.111111  0.000000   
679  0.111111  0.000000  0.000000  0.000000  0.111111  0.000000  0.000000   
680  0.444444  1.000000  1.000000  0.222222  0.666667  0.222222  0.777778   
681  0.333333  0.777778  0.555556  0.333333  0.222222  0.333333  1.000000   
682  0.333333  0.777778  0.777778  0.444444  0.333333  0.444444  1.000000   

           F8        F9  
0    0.000000  0.000000  
1    0.111111  0.000000  
2    0.000000  0.000000  
3    0.666667  0.000000  
4    0.000000  0.000000  
..        ...       ...  
678  0.000000  0.000000  
679  0.000000  0.000000  
680  1.000000  0.111111  
681  0.555556  0.000000  
682  0.333333  0.000000  

[683 rows x 9 columns]

## **Dividing the data into train (70%) and test (30%) split**

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(
    df, target, test_size=0.3, random_state=4, shuffle=True
)

## **Initialzing KNN Classifier**

In [7]:
k_values = [3, 5, 10]
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, Y_train)
    Y_pred = knn.predict(X_test)
    print(f"====== K-Value: {k} ======")
    print(f"Model Accuracy: {accuracy_score(Y_test, Y_pred)}")
    print(f"Confusion Matrix:\n {confusion_matrix(Y_test, Y_pred)}\n")
    print(f"Classification Report:\n {classification_report(Y_test, Y_pred)}\n")

====== K-Value: 3 ======
Model Accuracy: 0.9609756097560975
Confusion Matrix:
 [[126   6]
 [  2  71]]

Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.95      0.97       132
           4       0.92      0.97      0.95        73

    accuracy                           0.96       205
   macro avg       0.95      0.96      0.96       205
weighted avg       0.96      0.96      0.96       205


====== K-Value: 5 ======
Model Accuracy: 0.9512195121951219
Confusion Matrix:
 [[125   7]
 [  3  70]]

Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.95      0.96       132
           4       0.91      0.96      0.93        73

    accuracy                           0.95       205
   macro avg       0.94      0.95      0.95       205
weighted avg       0.95      0.95      0.95       205


====== K-Value: 10 ======
Model Accuracy: 0.9463414634146341
Confusion Matrix:
 [[125   7]